name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Build VSIX
      run: |
        vsce package --no-yarn
        echo "VSIX files in directory:"
        ls *.vsix
      
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension
        path: '*.vsix'
        retention-days: 5

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download VSIX artifact
      uses: actions/download-artifact@v4
      with:
        name: extension
        
    - name: Display structure of downloaded files
      run: ls -R
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.vsix
        fail_on_unmatched_files: true
        generate_release_notes: true

    - name: Debug Release
      run: |
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        echo "Files in current directory:"
        ls -l